name: flutter_bluetooth_serial_example
version: 0.4.0
description: Demonstrates how to use the `flutter_bluetooth_serial` plugin.
homepage: https://github.com/edufolly/flutter_bluetooth_serial/tree/master/example/

publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bluetooth_serial:
    path: ../
  permission_handler: ^11.3.1
  scoped_model: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
